CREATE DATABASE IF NOT EXISTS student_db;
USE student_db;

CREATE TABLE IF NOT EXISTS students (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(20) NOT NULL,
    age INT DEFAULT NULL,
    major VARCHAR(50) DEFAULT NULL,
    class_name VARCHAR(20) DEFAULT NULL
);